// discover.js — rewrites targets.js with low-TVL active Base Beefy vaults.
import { writeFileSync } from 'node:fs';

const MIN_TVL = 100;      // skip dead/dust vaults
const MAX_TVL = 100000;   // low-to-mid TVL — widen or narrow to taste
const LIMIT = 50;         // how many vaults to include

const [vaults, tvls] = await Promise.all([
  fetch('https://api.beefy.finance/vaults').then(r => r.json()),
  fetch('https://api.beefy.finance/tvl').then(r => r.json()),
]);

const baseTvl = tvls['8453'] || {};
const rows = vaults
  .filter(v => v.chain === 'base' && v.status === 'active' && v.strategy)
  .map(v => ({ id: v.id, strategy: v.strategy, tvl: baseTvl[v.id] || 0 }))
  .filter(v => v.tvl >= MIN_TVL && v.tvl <= MAX_TVL)
  .sort((a, b) => a.tvl - b.tvl)
  .slice(0, LIMIT);

if (rows.length === 0) { console.error('No vaults in range — targets.js unchanged.'); process.exit(1); }

const lines = rows.map(r =>
  `  { name: '${r.id}', address: '${r.strategy}' },  // TVL ~$${Math.round(r.tvl)}`
).join('\n');

writeFileSync('targets.js', `// targets.js — auto-generated by discover.js. Re-run to refresh.
export const BEEFY_STRATEGY_ABI = [
  'function callReward() view returns (uint256)',
  'function harvest(address callFeeRecipient) external',
  'function paused() view returns (bool)',
];

export const TARGETS = [
${lines}
];
`);
console.log(`Wrote targets.js with ${rows.length} vaults. Next: docker compose up -d --build`);
