// discover.js — rewrites a targets file with low-TVL active Beefy vaults.
// Usage: CHAIN=base LIMIT=50 node discover.js   (or CHAIN=optimism OUT=targets.optimism.js)
import { writeFileSync } from 'node:fs';

const CHAIN_IDS = { base: '8453', optimism: '10', mode: '34443', fraxtal: '252', arbitrum: '42161' };

const CHAIN = process.env.CHAIN || 'base';
const OUT = process.env.OUT || 'targets.js';
const MIN_TVL = Number(process.env.MIN_TVL || 100);      // skip dead/dust vaults
const MAX_TVL = Number(process.env.MAX_TVL || 100000);   // low-to-mid TVL — widen or narrow to taste
const LIMIT = Number(process.env.LIMIT || 50);           // how many vaults to include

if (!CHAIN_IDS[CHAIN]) { console.error(`Unknown chain '${CHAIN}'. Known: ${Object.keys(CHAIN_IDS).join(', ')}`); process.exit(1); }

const [vaults, tvls] = await Promise.all([
  fetch('https://api.beefy.finance/vaults').then(r => r.json()),
  fetch('https://api.beefy.finance/tvl').then(r => r.json()),
]);

const chainTvl = tvls[CHAIN_IDS[CHAIN]] || {};
const rows = vaults
  .filter(v => v.chain === CHAIN && v.status === 'active' && v.strategy)
  // CLM ("cow") vaults: callReward() reports total fees, not the caller's cut —
  // it overstates the payout ~1000x and every harvest loses money. Exclude them.
  .filter(v => !v.id.includes('cow'))
  .map(v => ({ id: v.id, strategy: v.strategy, tvl: chainTvl[v.id] || 0 }))
  .filter(v => v.tvl >= MIN_TVL && v.tvl <= MAX_TVL)
  .sort((a, b) => a.tvl - b.tvl)
  .slice(0, LIMIT);

if (rows.length === 0) { console.error(`No ${CHAIN} vaults in range — ${OUT} unchanged.`); process.exit(1); }

const lines = rows.map(r =>
  `  { name: '${r.id}', address: '${r.strategy}' },  // TVL ~$${Math.round(r.tvl)}`
).join('\n');

writeFileSync(OUT, `// ${OUT} — auto-generated by discover.js (chain: ${CHAIN}). Re-run to refresh.
export const BEEFY_STRATEGY_ABI = [
  'function callReward() view returns (uint256)',
  'function harvest(address callFeeRecipient) external',
  'function paused() view returns (bool)',
];

export const TARGETS = [
${lines}
];
`);
console.log(`Wrote ${OUT} with ${rows.length} ${CHAIN} vaults. Next: docker compose up -d --build`);
