// targets.js — auto-generated by discover.js (chain: base). Re-run to refresh.
export const BEEFY_STRATEGY_ABI = [
  'function callReward() view returns (uint256)',
  'function harvest(address callFeeRecipient) external',
  'function paused() view returns (bool)',
];

export const TARGETS = [
  { name: 'stakedao-base-superoethb', address: '0x825d8fF2FC98Ef7551C726899B4Eb2e281d98C57' },  // TVL ~$158
  { name: 'aerodrome-aero-tarot', address: '0x98E86bF5864064F32D5D564fbA796f5b8317F12b' },  // TVL ~$167
  { name: 'aerodrome-bold-lusd-new', address: '0x928D002329E1c4b3135251Cb319771f9CfCdaA63' },  // TVL ~$256
  { name: 'aerodrome-usdc-usdbc', address: '0x36D0De5E9401Fb6CB58d0A499a165921a3192241' },  // TVL ~$310
  { name: 'aerodrome-weth-kta', address: '0x506d3565d0AE39E87Fb48256a1e1fD90234d00A8' },  // TVL ~$322
  { name: 'aerodrome-weth-usdbc', address: '0x75d661F5dfe5B1855D1D6A62088615c1f945Cb59' },  // TVL ~$361
  { name: 'aerodrome-weth-klima', address: '0xd81785D344b12794c559Bd0Bd739b6aCF78C5879' },  // TVL ~$392
  { name: 'aerodrome-weth-degen', address: '0xC314990f1379fEe384Be9a74328C75Df8587aE77' },  // TVL ~$477
  { name: 'aerodrome-weth-ghst', address: '0xc327C62072EB5e02Dfb8eca6AF050185707A7C01' },  // TVL ~$506
  { name: 'curve-base-crv', address: '0x898Cb1986dD94D1AFc709aE88d3B97ec837756C3' },  // TVL ~$517
  { name: 'aerodrome-weth-drv', address: '0x354385E28C4F71F49885635AA528F0A262A9CC88' },  // TVL ~$586
  { name: 'aerodrome-cbbtc-champ', address: '0x2451301F0E1e616990a33728dDA588eC7385F600' },  // TVL ~$596
  { name: 'aerodrome-ion-weth', address: '0x377EfeB9F98B50F4c98F8F637161B512Eb873689' },  // TVL ~$612
  { name: 'aerodrome-weth-cbbtc', address: '0x106b9121d259fb46F1033BDBd29ad0C67650953C' },  // TVL ~$757
  { name: 'aerodrome-synd-weth', address: '0xD0544cD2b5B16CD23DBd1AB83710b82c46D059c0' },  // TVL ~$1034
  { name: 'aerodrome-usdc-cbbtc', address: '0x9Cb29Fac809413B633BC74f9F4b7b2180078dF91' },  // TVL ~$1039
  { name: 'aerodrome-lusd-pool', address: '0xb4823f5da6c37301C700C47517afc2A46ebD6c82' },  // TVL ~$1189
  { name: 'aerodrome-vvv-diem', address: '0xc2c94abF0F2128591F85cA46d3B986Beb9509A2b' },  // TVL ~$1241
  { name: 'aavev3-base-cbeth', address: '0x0300A8b1bb5E55F834a3Ce65c757f599679BE115' },  // TVL ~$1264
  { name: 'aerodrome-snx-usdc', address: '0xd35E45adbfBf05a3A8752A4526502173491FA030' },  // TVL ~$1272
  { name: 'aerodrome-weth-edel', address: '0xa69FF9C3e57b8385b1a786c4e40cf1c35601de79' },  // TVL ~$1878
  { name: 'aerodrome-weth-doginme', address: '0x5f396e58FE74114BED1ABD213516c519012F0a05' },  // TVL ~$2625
  { name: 'aerodrome-weth-qi', address: '0xACAD08b10542a65733bc2782572136338002E1e7' },  // TVL ~$3002
  { name: 'aerodrome-weth-fai', address: '0xD96EC76f4D6444C3FD0b187A641BFd7337742626' },  // TVL ~$3223
  { name: 'aerodrome-bold-usdc-new', address: '0xBceD90b591C94137c92bE5720170F991cef69826' },  // TVL ~$3533
  { name: 'aerodrome-weth-veil', address: '0xdbBc707cE40FF72ADaC8f87ED0CdF65554010062' },  // TVL ~$4212
  { name: 'aerodrome-weth-spx', address: '0x5DB73f13fe43B67F4941501d06Dc1f61Fa0D3B9b' },  // TVL ~$5030
  { name: 'aerodrome-tybg-weth', address: '0xe5c4CD247ac11F4E20583b4D3357627F4411D9A4' },  // TVL ~$5620
  { name: 'aerodrome-rsr-bsdeth', address: '0x693288C8f52752d921B03E8b0229c947f857D1f7' },  // TVL ~$6486
  { name: 'aerodrome-weth-wsteth', address: '0x7138333Bce12054c488F5bfCA2f92bd84b2E8f87' },  // TVL ~$7610
  { name: 'aerodrome-weeth-weth', address: '0x22f893A4ACFae28525A94e27C48Eb18A476D1059' },  // TVL ~$8497
  { name: 'aerodrome-tbtc-usdbc', address: '0xd740f387163E5E7a9D105b5e15f9383e2bb1aFcf' },  // TVL ~$10560
  { name: 'aerodrome-cbeth-weth', address: '0x5B429f261953416AD2bb8Aa76CE47725e09CD67E' },  // TVL ~$13139
  { name: 'stakedao-base-tricrypto', address: '0x516b6e27632091cf6279f6A0b3c6FcdA39d1FdEB' },  // TVL ~$16377
  { name: 'aerodrome-msusd-frxusd', address: '0x308B1d59BC2f1985bb44Fb64F67c1ddA99d19656' },  // TVL ~$17618
  { name: 'aerodrome-weth-npc', address: '0x71B5FCc6bd31Ae0C93a09122C603879B57F76eF9' },  // TVL ~$20471
  { name: 'morpho-v2-base-gauntlet-balanced-weth', address: '0x07421Db65caE0df71c5c173AdAB37282098eB6ef' },  // TVL ~$22518
  { name: 'aerodrome-hyusd-eusd', address: '0x09322bd95Ef32D9192C6DD3F58FA43446cfaA40D' },  // TVL ~$22867
  { name: 'aerodrome-weth-lrds', address: '0x0F03255Df313f85FAe2C34273010c22Bddc36cEa' },  // TVL ~$27182
  { name: 'aerodrome-weth-aero', address: '0x2de93273d06c344427f7Ef8992e5baB9ff971005' },  // TVL ~$27219
  { name: 'aerodrome-weth-mor', address: '0xB7D7A3dFd7bD7c4e0C9315E3f7d07d80b6d15Af6' },  // TVL ~$30522
  { name: 'alienbase-usdc-usdbc-narrow', address: '0xA28D5a576432687E9d6E8bEa54ab816a9a0f0293' },  // TVL ~$32254
  { name: 'aerodrome-weth-bwell', address: '0x5a6859C2f992B998837342d29911dD14E8DC2E1a' },  // TVL ~$33723
  { name: 'aerodrome-virtual-cbbtc', address: '0x48912528a1e2a5A1388B0E33AFCBF4065EB1089E' },  // TVL ~$37455
  { name: 'morpho-base-gauntlet-prime-usdc', address: '0xAbcD8A94Db286949B3D725bd3bC4601BC71cb369' },  // TVL ~$40145
  { name: 'morpho-base-steakhouse-prime-eurc', address: '0x97F0609d2d1fAdeD374FDACDf5fDf912fF0f656a' },  // TVL ~$41350
  { name: 'curve-base-4pool', address: '0xD345B2a911317CeD3A8d7A116F5AcD34A2073646' },  // TVL ~$42384
  { name: 'aerodrome-cbbtc-edge', address: '0xD1E1cDc52BC290F9bd3d50fc2D363B76eC0Dd0ee' },  // TVL ~$48515
  { name: 'aerodrome-aero-wsteth', address: '0x68d24F7C60D316EB27e116A9910902Ff23CD8f1E' },  // TVL ~$48936
  { name: 'aerodrome-aero-usdbc', address: '0xE329f2B51669dEDeB26E6AF0E901d0c8268EE619' },  // TVL ~$51788
];
