// targets.js — auto-generated by discover.js. Re-run to refresh.
export const BEEFY_STRATEGY_ABI = [
  'function callReward() view returns (uint256)',
  'function harvest(address callFeeRecipient) external',
  'function paused() view returns (bool)',
];

export const TARGETS = [
  { name: 'pancakeswap-cow-base-cbeth-cbbtc-vault', address: '0xA7cf5A6844fbd128C6b301d6B5acF46629407D66' },  // TVL ~$108
  { name: 'pancakeswap-cow-base-cbeth-weth-vault', address: '0x572aBb7496F170A3FBFedA91979bc7de6AE8baF8' },  // TVL ~$111
  { name: 'pancake-cow-base-virtual-opg-vault', address: '0x76BcabC0e291E994CDD956c715e80c71f76F565c' },  // TVL ~$117
  { name: 'aerodrome-cow-base-usdc-opg-vault', address: '0xEedfA33721FeF376425b5342eA89C1651b8d8517' },  // TVL ~$126
  { name: 'aerodrome-cow-base-mamo-cbbtc-vault', address: '0xf354C2665A6D7C9d290Fe8D746E5e212b555ee24' },  // TVL ~$126
  { name: 'aerodrome-cow-base-weth-veil-vault', address: '0x9Fe9b0C189e67463aaE8024788F6048abeAC1c84' },  // TVL ~$156
  { name: 'stakedao-base-superoethb', address: '0x825d8fF2FC98Ef7551C726899B4Eb2e281d98C57' },  // TVL ~$157
  { name: 'aerodrome-aero-tarot', address: '0x98E86bF5864064F32D5D564fbA796f5b8317F12b' },  // TVL ~$169
  { name: 'aero-cow-weth-spx-vault', address: '0xDF00878C03251E38aE37011f16c8722D99392Cf3' },  // TVL ~$187
  { name: 'aerodrome-cow-base-usdc-felix-vault', address: '0xB20BFA255CD68d06a5A7FD405e4a1e28205A8D38' },  // TVL ~$230
  { name: 'aerodrome-cow-base-seda-weth-vault', address: '0x2CfC31d786911Ad10E2af9b9fB985011FB74bb93' },  // TVL ~$247
  { name: 'aerodrome-bold-lusd-new', address: '0x928D002329E1c4b3135251Cb319771f9CfCdaA63' },  // TVL ~$256
  { name: 'aerodrome-usdc-usdbc', address: '0x36D0De5E9401Fb6CB58d0A499a165921a3192241' },  // TVL ~$310
  { name: 'aerodrome-weth-kta', address: '0x506d3565d0AE39E87Fb48256a1e1fD90234d00A8' },  // TVL ~$318
  { name: 'aero-cow-weth-ethfi-vault', address: '0x87308630CBa79d65BABaE73f00aD7E18dBAd7eB9' },  // TVL ~$350
  { name: 'aerodrome-weth-usdbc', address: '0x75d661F5dfe5B1855D1D6A62088615c1f945Cb59' },  // TVL ~$359
  { name: 'aerodrome-cow-base-weth-litkey-vault', address: '0x14731536D1bA56e3a5247426CcdF22dBf44a249D' },  // TVL ~$386
  { name: 'aerodrome-weth-klima', address: '0xd81785D344b12794c559Bd0Bd739b6aCF78C5879' },  // TVL ~$387
  { name: 'aerodrome-weth-degen', address: '0xC314990f1379fEe384Be9a74328C75Df8587aE77' },  // TVL ~$455
  { name: 'aerodrome-cow-base-cbbtc-zen-vault', address: '0xcB1eC6a5EaaE09033Ce5ea64099B969A956a0613' },  // TVL ~$490
  { name: 'aerodrome-cow-base-aora-usdc-vault', address: '0x0F4b1Df3395f91A2Ebd7108b36Bcc9e7ddDBDf24' },  // TVL ~$493
  { name: 'aerodrome-cow-base-tea-usdc-vault', address: '0x2D845B976D07C40D576913C2c9D637e127449508' },  // TVL ~$501
  { name: 'aerodrome-weth-ghst', address: '0xc327C62072EB5e02Dfb8eca6AF050185707A7C01' },  // TVL ~$516
  { name: 'curve-base-crv', address: '0x898Cb1986dD94D1AFc709aE88d3B97ec837756C3' },  // TVL ~$519
  { name: 'aero-cow-bitcoin-weth-vault', address: '0x72972C11dC5a86f8619F0609ED492c8E2C9541CA' },  // TVL ~$570
  { name: 'aerodrome-weth-drv', address: '0x354385E28C4F71F49885635AA528F0A262A9CC88' },  // TVL ~$577
  { name: 'aerodrome-ion-weth', address: '0x377EfeB9F98B50F4c98F8F637161B512Eb873689' },  // TVL ~$606
  { name: 'aerodrome-cbbtc-champ', address: '0x2451301F0E1e616990a33728dDA588eC7385F600' },  // TVL ~$622
  { name: 'aerodrome-cow-base-vvv-diem-v2-vault', address: '0x7061F70d97675C32e4Db69CB6A4b3D2a2656e8d6' },  // TVL ~$643
  { name: 'aerodrome-cow-base-weth-well-vault', address: '0x5fA8942eBA5d258f8E42C6978D97c67277Dd0caf' },  // TVL ~$665
  { name: 'aerodrome-cow-base-synd-weth-vault', address: '0xe72Ab78CE1c366874307A8a329a25848701960Ba' },  // TVL ~$685
  { name: 'aerodrome-cow-base-usdc-sapien-vault', address: '0x7e2323E587B7e97CE60332de5d9743Bde2aBA1b9' },  // TVL ~$699
  { name: 'aero-cow-miggles-weth-vault', address: '0x05f9f222005Bb134227f3923859fCb572d951904' },  // TVL ~$717
  { name: 'aerodrome-weth-cbbtc', address: '0x106b9121d259fb46F1033BDBd29ad0C67650953C' },  // TVL ~$748
  { name: 'aero-cow-eigen-weth-vault', address: '0xE54de66f5eEE20d17172ab304BF3d7171936d25c' },  // TVL ~$779
  { name: 'aerodrome-cow-base-up-usdc-vault', address: '0xa2f4615f691A7b8FeB741212bb76932d0AaB92AD' },  // TVL ~$807
  { name: 'aerodrome-cow-base-fun-usdc-vault', address: '0xfED48ED5CF18f05D63d0De570f1a2F17CE1a9602' },  // TVL ~$828
  { name: 'aerodrome-cow-base-hype-weth-vault', address: '0xde0b782070B64ebB33f8FE94d227070319f92894' },  // TVL ~$866
  { name: 'aerodrome-cow-base-usdc-avail-vault', address: '0xE75c105F13ca763aF399913f90F5aF7341934f33' },  // TVL ~$889
  { name: 'aerodrome-cow-base-cbbtc-weth-vault', address: '0x96Dc37e428D607d1DBDfa764a4D11fD4C3034e2b' },  // TVL ~$898
  { name: 'aerodrome-cow-base-up-cbbtc-vault-v2', address: '0x0eB52bec5C73048bb83B9Aa7524e476cE2ce4F18' },  // TVL ~$917
  { name: 'aerodrome-cow-base-usdc-weth-v2-vault', address: '0x29B9Ac88aeE9B16Fb98218aF5b8c11Cf42a3DcB3' },  // TVL ~$931
  { name: 'aerodrome-usdc-cbbtc', address: '0x9Cb29Fac809413B633BC74f9F4b7b2180078dF91' },  // TVL ~$1032
  { name: 'aerodrome-synd-weth', address: '0xD0544cD2b5B16CD23DBd1AB83710b82c46D059c0' },  // TVL ~$1045
  { name: 'aerodrome-cow-base-weth-link-vault', address: '0x18769a744Be966F9db95C4a0194C7938891Ebb64' },  // TVL ~$1053
  { name: 'aerodrome-cow-base-ctr-usdc-vault', address: '0x3baf4ba6cC85e6171F7ACD2342b149BFE7d4A45b' },  // TVL ~$1116
  { name: 'aerodrome-cow-base-weth-pendle-vault', address: '0x22fec056A06B6d5d8bFf585bcf986a2EdD2c34e8' },  // TVL ~$1166
  { name: 'aerodrome-cow-base-usdc-odos-vault', address: '0xfD4E687706D7869b635Ba939303d4D091e53d873' },  // TVL ~$1181
  { name: 'aerodrome-lusd-pool', address: '0xb4823f5da6c37301C700C47517afc2A46ebD6c82' },  // TVL ~$1181
  { name: 'aero-cow-weth-keycat-vault', address: '0xb1B5D93ef21E0A355968a59d2Ca39724aCBD2306' },  // TVL ~$1220
];
